name: poundwise
description: "A currency exchange tracker."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  connectivity_plus: ^7.3.1
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.3.0
  go_router: ^18.0.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/licenses/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/poundwise_app_icon.png
  adaptive_icon_background: '#123F32'
  adaptive_icon_foreground: assets/images/poundwise_app_icon_foreground.png
  remove_alpha_ios: true
